<?php

namespace Database\Seeders;

use App\Models\Desa;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class DesaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $desa = [
            [
                'kecamatan_id'      => 1,
                'nama_desa'      => 'Kampung Dalam',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kecamatan_id'      => 1,
                'nama_desa'      => 'Kampung Rempak',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kecamatan_id'      => 1,
                'nama_desa'      => 'Langkai',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kecamatan_id'      => 1,
                'nama_desa'      => 'Tumang',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kecamatan_id'      => 1,
                'nama_desa'      => 'Merempan Hulu	',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kecamatan_id'      => 1,
                'nama_desa'      => 'Rawang Air Putih	',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kecamatan_id'      => 1,
                'nama_desa'      => 'Suak Lanjut	',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kecamatan_id'      => 1,
                'nama_desa'      => 'Buantan Besar	',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kecamatan_id'      => 2,
                'nama_desa'      => 'Sungai Apit	',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kecamatan_id'      => 2,
                'nama_desa'      => 'Teluk Lanus	',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kecamatan_id'      => 2,
                'nama_desa'      => 'Tanjung Kuras	',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kecamatan_id'      => 2,
                'nama_desa'      => 'Parit I/II	',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kecamatan_id'      => 2,
                'nama_desa'      => 'Teluk Mesjid	',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kecamatan_id'      => 2,
                'nama_desa'      => 'Sungai Kayu Ara	',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kecamatan_id'      => 2,
                'nama_desa'      => 'Lalang	',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kecamatan_id'      => 2,
                'nama_desa'      => 'Mengkapan	',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kecamatan_id'      => 2,
                'nama_desa'      => 'Sungai Rawa	',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kecamatan_id'      => 2,
                'nama_desa'      => 'Penyengat	',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kecamatan_id'      => 2,
                'nama_desa'      => 'Teluk Batil	',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kecamatan_id'      => 2,
                'nama_desa'      => 'Bunsur	',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kecamatan_id'      => 2,
                'nama_desa'      => 'Harapan	',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kecamatan_id'      => 2,
                'nama_desa'      => 'Kayu Ara Permai	',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kecamatan_id'      => 2,
                'nama_desa'      => 'Rawa Mekar Jaya	',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kecamatan_id'      => 3,
                'nama_desa'      => 'Minas Jaya	',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kecamatan_id'      => 3,
                'nama_desa'      => 'Minas Timur	',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kecamatan_id'      => 3,
                'nama_desa'      => 'Minas Barat	',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kecamatan_id'      => 3,
                'nama_desa'      => 'Mandi Angin	',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kecamatan_id'      => 3,
                'nama_desa'      => 'Rantau Bertuah	',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kecamatan_id'      => 4,
                'nama_desa'      => 'Perawang	',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kecamatan_id'      => 4,
                'nama_desa'      => 'Tualang	',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kecamatan_id'      => 4,
                'nama_desa'      => 'Pinang Sebatang	',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kecamatan_id'      => 4,
                'nama_desa'      => 'Meredan	',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kecamatan_id'      => 4,
                'nama_desa'      => 'Pinang Sebatang Timur	',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kecamatan_id'      => 4,
                'nama_desa'      => 'Pinang Sebatang Barat	',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kecamatan_id'      => 4,
                'nama_desa'      => 'Meredan Barat	',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kecamatan_id'      => 4,
                'nama_desa'      => 'Perawang Barat	',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kecamatan_id'      => 4,
                'nama_desa'      => 'Tualang Timur	',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kecamatan_id'      => 5,
                'nama_desa'      => 'Muara Kelantan	',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kecamatan_id'      => 5,
                'nama_desa'      => 'Teluk Lancang	',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kecamatan_id'      => 5,
                'nama_desa'      => 'Sungai Selodang	',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kecamatan_id'      => 5,
                'nama_desa'      => 'Olak	',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kecamatan_id'      => 5,
                'nama_desa'      => 'Lubuk Jering	',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kecamatan_id'      => 5,
                'nama_desa'      => 'Muara Bungkal	',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kecamatan_id'      => 5,
                'nama_desa'      => 'Lubuk Umbut	',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kecamatan_id'      => 5,
                'nama_desa'      => 'Bencah Umbai	',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kecamatan_id'      => 5,
                'nama_desa'      => 'Tasik Betung	',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kecamatan_id'      => 6,
                'nama_desa'      => 'Dayun	',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kecamatan_id'      => 6,
                'nama_desa'      => 'Banjar Seminai	',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kecamatan_id'      => 6,
                'nama_desa'      => 'Teluk Merbau	',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kecamatan_id'      => 6,
                'nama_desa'      => 'Merangkai	',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kecamatan_id'      => 6,
                'nama_desa'      => 'Lubuk Tilan	',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kecamatan_id'      => 6,
                'nama_desa'      => 'Berumbung Baru	',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kecamatan_id'      => 6,
                'nama_desa'      => 'Pangkalan Makmur	',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kecamatan_id'      => 6,
                'nama_desa'      => 'Buana Makmur	',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kecamatan_id'      => 6,
                'nama_desa'      => 'Suka Mulya	',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kecamatan_id'      => 6,
                'nama_desa'      => 'Sawit Permai	',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kecamatan_id'      => 6,
                'nama_desa'      => 'Sialang Sakti	',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kecamatan_id'      => 7,
                'nama_desa'      => 'Kerinci Kanan	',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kecamatan_id'      => 7,
                'nama_desa'      => 'Kerinci Kiri	',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kecamatan_id'      => 7,
                'nama_desa'      => 'Buana Bakti	',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kecamatan_id'      => 7,
                'nama_desa'      => 'Bukit Harapan	',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kecamatan_id'      => 7,
                'nama_desa'      => 'Kumbara Utama	',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kecamatan_id'      => 7,
                'nama_desa'      => 'Bukit Agung	',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kecamatan_id'      => 7,
                'nama_desa'      => 'Simpang Perak Jaya	',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kecamatan_id'      => 7,
                'nama_desa'      => 'Buatan Baru	',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kecamatan_id'      => 7,
                'nama_desa'      => 'Gabung Makmur	',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kecamatan_id'      => 7,
                'nama_desa'      => 'Jati Mulya	',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kecamatan_id'      => 7,
                'nama_desa'      => 'Seminai	',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kecamatan_id'      => 7,
                'nama_desa'      => 'Delima Jaya	',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kecamatan_id'      => 8,
                'nama_desa'      => 'Bungaraya	',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kecamatan_id'      => 8,
                'nama_desa'      => 'Jati Baru	',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kecamatan_id'      => 8,
                'nama_desa'      => 'Jayapura	',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kecamatan_id'      => 8,
                'nama_desa'      => 'Kemuning Muda	',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kecamatan_id'      => 8,
                'nama_desa'      => 'Buantan Lestari	',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kecamatan_id'      => 8,
                'nama_desa'      => 'Tuah Indrapura	',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kecamatan_id'      => 8,
                'nama_desa'      => 'Langsat Permai	',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kecamatan_id'      => 8,
                'nama_desa'      => 'Temusai	',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kecamatan_id'      => 8,
                'nama_desa'      => 'Dayang Sur	',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kecamatan_id'      => 8,
                'nama_desa'      => 'Suak Merambai	',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kecamatan_id'      => 9,
                'nama_desa'      => 'Pangkalan Pisang	',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kecamatan_id'      => 9,
                'nama_desa'      => 'Kuala Gasib	',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kecamatan_id'      => 9,
                'nama_desa'      => 'Teluk Rimba	',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kecamatan_id'      => 9,
                'nama_desa'      => 'Buatan I	',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kecamatan_id'      => 9,
                'nama_desa'      => 'Buatan II',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kecamatan_id'      => 9,
                'nama_desa'      => 'Sengkemang	',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kecamatan_id'      => 9,
                'nama_desa'      => 'Rantau Panjang	',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kecamatan_id'      => 9,
                'nama_desa'      => 'Empang Pandan	',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kecamatan_id'      => 9,
                'nama_desa'      => 'Keranji Guguh	',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kecamatan_id'      => 9,
                'nama_desa'      => 'Sri Gemilang	',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kecamatan_id'      => 9,
                'nama_desa'      => 'Tasik Seminai	',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kecamatan_id'      => 10,
                'nama_desa'      => 'Simpang Belutu	',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kecamatan_id'      => 10,
                'nama_desa'      => 'Telaga Sam - Sam	',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kecamatan_id'      => 10,
                'nama_desa'      => 'Kandis Kota	',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kecamatan_id'      => 10,
                'nama_desa'      => 'Belutu	',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kecamatan_id'      => 10,
                'nama_desa'      => 'Kandis	',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kecamatan_id'      => 10,
                'nama_desa'      => 'Sam-Sam	',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kecamatan_id'      => 10,
                'nama_desa'      => 'Bekalar	',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kecamatan_id'      => 10,
                'nama_desa'      => 'Jambai Makmur	',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kecamatan_id'      => 10,
                'nama_desa'      => 'Sungai Gondang	',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kecamatan_id'      => 10,
                'nama_desa'      => 'Pencing Bekulo	',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kecamatan_id'      => 10,
                'nama_desa'      => 'Libo Jaya	',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kecamatan_id'      => 11,
                'nama_desa'      => 'Lubuk Dalam	',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kecamatan_id'      => 11,
                'nama_desa'      => 'Rawang Kao	',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kecamatan_id'      => 11,
                'nama_desa'      => 'Sri Gading	',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kecamatan_id'      => 11,
                'nama_desa'      => 'Sialang Baru	',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kecamatan_id'      => 11,
                'nama_desa'      => 'Sialang Palas	',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kecamatan_id'      => 11,
                'nama_desa'      => 'Empang Baru	',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kecamatan_id'      => 11,
                'nama_desa'      => 'Awang Kao Barat	',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kecamatan_id'      => 12,
                'nama_desa'      => 'Bandar Sungai	',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kecamatan_id'      => 12,
                'nama_desa'      => 'Rempak	',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kecamatan_id'      => 12,
                'nama_desa'      => 'Belading	',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kecamatan_id'      => 12,
                'nama_desa'      => 'Sungai Tengah	',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kecamatan_id'      => 12,
                'nama_desa'      => 'Laksamana	',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kecamatan_id'      => 12,
                'nama_desa'      => 'Sabak Permai	',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kecamatan_id'      => 12,
                'nama_desa'      => 'Bandar Pedada	',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kecamatan_id'      => 12,
                'nama_desa'      => 'Selat Guntung	',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kecamatan_id'      => 13,
                'nama_desa'      => 'Sungai Mempura	',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kecamatan_id'      => 13,
                'nama_desa'      => 'Kota Ringin	',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kecamatan_id'      => 13,
                'nama_desa'      => 'Paluh	',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kecamatan_id'      => 13,
                'nama_desa'      => 'Benteng Hilir	',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kecamatan_id'      => 13,
                'nama_desa'      => 'Benteng Hulu	',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kecamatan_id'      => 13,
                'nama_desa'      => 'Kampung Tengah	',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kecamatan_id'      => 13,
                'nama_desa'      => 'Merempan Hilir	',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kecamatan_id'      => 13,
                'nama_desa'      => 'Teluk Merempan	',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kecamatan_id'      => 14,
                'nama_desa'      => 'Sungai Berbari	',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kecamatan_id'      => 14,
                'nama_desa'      => 'Sungai Limau	',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kecamatan_id'      => 14,
                'nama_desa'      => 'Dosan	',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kecamatan_id'      => 14,
                'nama_desa'      => 'Benayah	',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kecamatan_id'      => 14,
                'nama_desa'      => 'Pebadaran	',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kecamatan_id'      => 14,
                'nama_desa'      => 'Dusun Pusaka	',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kecamatan_id'      => 14,
                'nama_desa'      => 'Perincit	',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
        ];

        Desa::insert($desa);
    }
}
